Feat/animal resonate
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16 pull request #24
Opened 2024-11-17 19:14 UTC by ygr4789

2024-11-26 14:50 UTC, silee1103 requested changes
기능은 다 정상적으로 작동합니다!
다만 변수화(1)와 성능(2)에 관해 총 3개 review 드렸습니다.
필요없다싶은 부분은 말씀해주세요

2024-11-26 14:50 UTC, silee1103 commented on Assets/02.Scripts/Objects/AnimalController.cs
나중에 customizing이 쉽게 되도록 아래의 값들을 변수화 시켜주면 좋을 것 같습니다
1. FollowPathBehavior의 random waiting time range (minPathWaitTime, maxPathWaitTime), followPathThreshold 값
2. CollidingFront의 checkDistance, numDetectionSteps, maxDetectionAngle (raycast가 너무 많으면 성능에 문제가 있을 수도 있을 것 같아, 상황에 따라 최적화를 위해)

2024-11-26 14:50 UTC, silee1103 commented on Assets/02.Scripts/Objects/AnimalController.cs
> +                StickToGround();
sticktoground가 결국 cost가 좀 큰 것 같아서 아래 두 가지 방법 같은 것을 고려해보면 어떨까 싶습니다.
1. 일정 시간간격마다 호출
```
  float timeSinceLastStick = 0f;
  while (Vector3.Distance(transform.position, targetPosition) > 0.5f)
  {
      if (!CollidingFront())
          transform.position = Vector3.MoveTowards(transform.position, targetPosition, idleSpeed * Time.deltaTime);
  
      // 일정 시간 간격마다 StickToGround 호출
      timeSinceLastStick += Time.deltaTime;
      if (timeSinceLastStick > 0.1f)
      {
          StickToGround();
          timeSinceLastStick = 0f;
      }
  }
```

2. 지형 변화가 클 때 호출
```
private Vector3 lastGroundPosition = Vector3.zero;
private void StickToGround()
{
    // 기존 StickToGround 로직...
    if (Mathf.Abs(transform.position.y - lastGroundPosition.y) > 0.01f)
    {
        // 지면 위치를 업데이트
        lastGroundPosition = transform.position;
    }
}
```

2024-11-26 14:50 UTC, silee1103 commented on Assets/02.Scripts/Objects/AnimalController.cs
> +    private bool CollidingFront()
raycast를 많이 쓰는 것이 추후 성능에 문제가 될 수 있는 점을 감안해, 아래와 같은 제안을 드립니다.
1. 탐지 범위 줄이기 (혹은 변수화로 최적화)
```
float maxDetectionAngle = 45f; // 탐지 각도
int numDetectionSteps = 5; // 레이 수
```
2. 중심 레이 먼저 쏘기
```
private bool CollidingFront()
{
    Vector3 rayOrigin = transform.position + transform.up * colliderOriginHeight;
    float checkDistance = 5f;

    // 먼저 중심선으로 충돌 여부를 확인
    if (Physics.Raycast(rayOrigin, transform.forward, checkDistance, groundLayer))
    {
        return true;
    }

    // 충돌이 없으면 추가적인 각도 탐지 수행
    for (int i = -numStep; i <= numStep; i++)
    {
        float angle = detectionAngle * i / numStep;
        Vector3 direction = Quaternion.Euler(0, angle, 0) * transform.forward;
        if (Physics.Raycast(rayOrigin, direction, checkDistance, groundLayer))
        {
            return true;
        }
    }

    return false;
}
```
3. collider 사용: 동물 앞에 collider 배치
```
[SerializeField] private Collider detectionCollider; // 장애물 감지용 콜라이더

private bool CollidingFront()
{
    // detectionCollider와 objectLayer가 충돌했는지 확인
    return Physics.CheckBox(detectionCollider.bounds.center, detectionCollider.bounds.extents, transform.rotation, objectLayer);
}
```

2024-11-27 15:17 UTC, ygr4789 commented on Assets/02.Scripts/Objects/AnimalController.cs
1. 848b5cd23c2e0bf609672a8486690967e9584b1a
2. Rigidbody로 대체할 예정

2024-11-27 15:18 UTC, ygr4789 commented on Assets/02.Scripts/Objects/AnimalController.cs
> +                StickToGround();
프레임 당 지정된 레이어 Raycast 4회라서 이 부분은 cost가 크지는 않은 것 같습니다

2024-11-27 15:20 UTC, ygr4789 commented on Assets/02.Scripts/Objects/AnimalController.cs
> +    private bool CollidingFront()
플레이어 간섭 문제가 해결되어 추후 Rigidbody로 대체할 예정

2024-11-27 16:49 UTC, silee1103 approved these changes
#37 문제를 제외하고 모두 정상적으로 작동하는 것 같습니다.
수고하셨습니다!

2024-11-27 16:50 UTC, merged