Feat/resonate fine tuning
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16 pull request #27
Opened 2024-11-19 14:34 UTC by silee1103

2024-11-29 14:24 UTC, ygr4789 commented on Assets/02.Scripts/Managers/EffectManager.cs
> +    [SerializeField] public ParticleSystem ripplesEffectPrefab;
외부 클래스에서의 호출이 없어 보여 `private`로 수정 가능해 보입니다

2024-11-29 16:18 UTC, ygr4789 requested changes
이펙트 회전 문제가 잘 해결되었습니다.
탐지 범위에서 벗어난 직후 다시 들어온 경우에도 원활하게 작동하는 것을 확인하였습니다.

다만 이펙트 크기 관련하여 문제가 남아있어 merge 전에 수정이 필요합니다.

2024-11-29 16:18 UTC, ygr4789 commented on Assets/02.Scripts/Managers/EffectManager.cs
> +    [SerializeField] public ParticleSystem ripplesEffectPrefab;
`private`으로 수정 가능해 보입니다

2024-11-29 16:18 UTC, ygr4789 commented on Assets/02.Scripts/Managers/EffectManager.cs
> +        Renderer[] renderers = target.GetComponentsInChildren<Renderer>();
`TriggerRipples`에서 호출할 때 Bounds를 받아오면 반복을 없앨 수 있는 연산 같습니다.

또한 `GetComponentsInChildren<Renderer>`호출 시점에 이미 Ripple 오브젝트가 생성된 상태라서 이것이 Renderer에 포함되어 `totalBounds`의 크기가 매우 크게 계산됩니다. Renderer 대신 Collider를 사용해도 괜찮아 보입니다.

![image](https://github.com/user-attachments/assets/12fd7125-8e8f-45f1-8ebe-5ad0d2f42902)

![image](https://github.com/user-attachments/assets/110ac847-906f-4f76-aad7-37c589bfbe0b)

2024-11-29 16:18 UTC, ygr4789 commented on Assets/02.Scripts/Objects/TreeController.cs
> +        GameManager.em.UpdateRipplePosition(transform, transform.position + Vector3.up * 0.5f);
Update마다 호출될 필요가 없어 보입니다. `ResonatableObject`가 이펙트 발생 지점 offset을 property로 가지고 있도록 하고, `TriggerRipples`에서 `newEffect.transform`에 반영하는 방식이 더 좋을 것 같습니다.

2024-11-29 16:18 UTC, ygr4789 commented on Assets/02.Scripts/Objects/ResonatableObject.cs
> +    public int colliderNum = 0;
`private`으로 수정 가능해 보입니다.

2024-11-29 16:18 UTC, ygr4789 commented on Assets/02.Scripts/Managers/EffectManager.cs
오브젝트의 Scale을 작게 지정했을 경우 이펙트의 크기가 과도하게 커지는 버그가 있습니다. Bounding Box 계산 문제 또는 localScale로 인한 문제 같습니다.

- Rock의 Scale을 0.5로 지정한 경우
![스크린샷 2024-11-30 000124](https://github.com/user-attachments/assets/fbfabae4-4147-48b9-8d87-675933fd7097)

- Rock의 Scale을 0.1로 지정한 경우
![스크린샷 2024-11-30 000151](https://github.com/user-attachments/assets/aec925e0-ea04-438e-b18e-cf9f7b877181)

2024-11-30 11:32 UTC, silee1103 commented on Assets/02.Scripts/Managers/EffectManager.cs
> +    [SerializeField] public ParticleSystem ripplesEffectPrefab;
수정하였습니다

2024-11-30 11:32 UTC, silee1103 commented on Assets/02.Scripts/Managers/EffectManager.cs
> +        Renderer[] renderers = target.GetComponentsInChildren<Renderer>();
Renderer 대신 Collider를 사용하였습니다

2024-11-30 11:33 UTC, silee1103 commented on Assets/02.Scripts/Objects/ResonatableObject.cs
> +    public int colliderNum = 0;
수정하였습니다

2024-11-30 11:38 UTC, silee1103 commented on Assets/02.Scripts/Managers/EffectManager.cs
collider로 변경하고 minParticleSize을 작게 하니 해결되었습니다

2024-11-30 12:55 UTC, silee1103 commented on Assets/02.Scripts/Objects/TreeController.cs
> +        GameManager.em.UpdateRipplePosition(transform, transform.position + Vector3.up * 0.5f);
각 resonatable마다 offset vector를 가지고 있고 그걸 effect Manager에 넘겨주는 식으로 바꿈
이때 playmanager에서 tab으로 바꿀 때도 GetComponenet로 resonatable에서 offset을 가져오는 비효율성이 존재하긴 하지만 큰 cost가 아니라 생각하여 넘김

2024-12-01 05:40 UTC, ygr4789 commented
이펙트 크기 조정 정상 동작하는 것 확인했습니다.

2024-12-01 05:40 UTC, ygr4789 approved these changes

2024-12-01 05:44 UTC, merged