apply sound
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16 pull request #49
Opened 2024-11-30 16:58 UTC by RayBean1022

## Description

## Related Issue

## Changes Made

- [ ] Change 1

## How to Test This Branch

## Screenshots (if applicable)

## Additional Notes

2024-12-03 12:00 UTC, silee1103 requested changes
혹시 import한 Assets Footsteps - Essentials, impactSounds 사용하지 않는 것은 삭제 가능할까요?

2024-12-03 12:30 UTC, silee1103 requested changes

2024-12-03 12:30 UTC, silee1103 commented on Assets/02.Scripts/Objects/PlateController.cs
unpress 될 때의 sound도 있으면 좋을 것 같습니다!

2024-12-03 12:30 UTC, silee1103 commented on Assets/02.Scripts/Objects/TreeController.cs
> +        GameManager.sm.PlaySound("collapse");
나무의 크기가 변하는 소리에 비해 소리 크기가 너무 작은 것 같습니다

2024-12-03 12:30 UTC, silee1103 commented on Assets/02.Scripts/Objects/TreeController.cs
나무의 크기가 변화하며 효과음이 발생할 때 player의 소리가 사라지는 에러가 있는 것 같습니다

2024-12-04 09:37 UTC, RayBean1022 commented on Assets/02.Scripts/Objects/TreeController.cs
> +        GameManager.sm.PlaySound("collapse");
2배로 키웠습니다

2024-12-04 10:19 UTC, RayBean1022 commented on Assets/02.Scripts/Objects/PlateController.cs
추가 완료

2024-12-04 10:22 UTC, RayBean1022 commented on Assets/02.Scripts/Objects/TreeController.cs
제가 테스트할 때는 잘 모르겠는데 상황 설명 더 부탁드려도 될까요

2024-12-04 13:41 UTC, silee1103 commented on Assets/02.Scripts/Objects/TreeController.cs
TestScene에 SoundManager를 가져와 실행하니 그러한 현상이 발생합니다.
나무의 크기를 바꾸는 순간 플레이어의 연주소리가 작아집니다

2024-12-05 06:53 UTC, RayBean1022 commented on Assets/02.Scripts/Objects/TreeController.cs
저는 잘 모르겠는데 심각한 거 아니면 넘기는 거 어떤가용..

2024-12-06 06:02 UTC, silee1103 commented on Assets/02.Scripts/Objects/TreeController.cs
그럼 일단 그렇게 하겠습니다!

2024-12-06 06:02 UTC, silee1103 approved these changes

2024-12-06 06:10 UTC, merged